from typing import Protocol


class ICache(Protocol):
    async def get(self, key: str) -> dict | list | None: ...
    async def set(self, key: str, value: dict | list, ttl: int = 300) -> None: ...
    async def delete(self, key: str) -> None: ...
