services:

  traefik:
    image: traefik:v3.4
    container_name: timekeep_traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@24timekeep.ru"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/letsencrypt/acme.json

  db:
    image: postgres:16
    container_name: timekeep_db
    environment:
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - web
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: timekeep_redis
    restart: always
    networks:
      - web

  backend:
    build:
      context: ./backend
    container_name: timekeep_backend
    command: sh -c "alembic upgrade head && uvicorn src.presentation.app:create_app --host 0.0.0.0 --port 8080 --factory"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - web
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`24timekeep.ru`) && PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=8080

  frontend:
    build:
      context: ./frontend
    container_name: timekeep_frontend
    restart: always
    networks:
      - web
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`24timekeep.ru`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt
      - traefik.http.services.frontend.loadbalancer.server.port=3000

volumes:
  postgres_data:

networks:
  web:
    external: false