"""init

Revision ID: 12ed78699f90
Revises: 
Create Date: 2026-05-31 01:31:47.198896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ed78699f90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name_genitive', sa.VARCHAR(length=64), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['users.id'], name='fk_organization_boss_id', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__organizations')),
    sa.UniqueConstraint('name', name=op.f('uq__organizations__name')),
    sa.UniqueConstraint('name_genitive', name=op.f('uq__organizations__name_genitive'))
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('departments_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__departments')),
    sa.UniqueConstraint('name', name=op.f('uq__departments__name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(length=64), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=64), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('patronymic', sa.VARCHAR(length=64), nullable=False),
    sa.Column('position', sa.VARCHAR(length=64), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMIN', 'SUPER_ADMIN', name='role'), nullable=False),
    sa.Column('rank', sa.Enum('PRIVATE', 'JUNIOR_SERGEANT', 'SERGEANT', 'SENIOR_SERGEANT', 'FOREMAN', 'WARRANT_OFFICER', 'SENIOR_WARRANT_OFFICER', 'LIEUTENANT', 'SENIOR_LIEUTENANT', 'CAPTAIN', 'MAJOR', 'LIEUTENANT_COLONEL', 'COLONEL', 'MAJOR_GENERAL', 'LIEUTENANT_GENERAL', 'COLONEL_GENERAL', name='rank'), nullable=False),
    sa.Column('work_mode', sa.Enum('DAILY', 'SHIFT', name='workmode'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('users_department_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('users_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('login', name=op.f('uq__users__login'))
    )
    op.create_table('day_offs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='dayoffstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('day_offs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__day_offs'))
    )
    op.create_table('overtimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('used_hours', sa.Float(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', name='overtimestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('overtimes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__overtimes'))
    )
    op.create_table('day_off_overtimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_off_id', sa.Integer(), nullable=False),
    sa.Column('overtime_id', sa.Integer(), nullable=False),
    sa.Column('used_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['day_off_id'], ['day_offs.id'], name=op.f('day_off_overtimes_day_off_id_fkey')),
    sa.ForeignKeyConstraint(['overtime_id'], ['overtimes.id'], name=op.f('day_off_overtimes_overtime_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__day_off_overtimes'))
    )
    op.create_index(op.f('ix__day_off_overtimes_day_off_id'), 'day_off_overtimes', ['day_off_id'], unique=False)
    op.create_index(op.f('ix__day_off_overtimes_overtime_id'), 'day_off_overtimes', ['overtime_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__day_off_overtimes_overtime_id'), table_name='day_off_overtimes')
    op.drop_index(op.f('ix__day_off_overtimes_day_off_id'), table_name='day_off_overtimes')
    op.drop_table('day_off_overtimes')
    op.drop_table('overtimes')
    op.drop_table('day_offs')
    op.drop_table('users')
    op.drop_table('departments')
    op.drop_table('organizations')
    # ### end Alembic commands ###
